Repository jhsnex123/moimeasy, pull requests merged in 2024-12, with the labels that each got.

#1 chore: 프론트엔드 초기 세팅
  frontend/.gitignore
  frontend/README.md
  frontend/index.html
  frontend/jsconfig.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/src/App.vue
  frontend/src/assets/base.css
  frontend/src/assets/logo.svg
  frontend/src/assets/main.css
  frontend/src/components/HelloWorld.vue
  frontend/src/components/TheWelcome.vue
  frontend/src/components/WelcomeItem.vue
  frontend/src/components/icons/IconCommunity.vue
  frontend/src/components/icons/IconDocumentation.vue
  frontend/src/components/icons/IconEcosystem.vue
  frontend/src/components/icons/IconSupport.vue
  frontend/src/components/icons/IconTooling.vue
  frontend/src/main.js
  frontend/vite.config.js
Labels: good first issue

#8 chore: 패키지 추가, 수정
  build.gradle
  src/main/java/com/kosa/moimeasy/invitation/controller/InvitationController.java
  src/main/java/com/kosa/moimeasy/invitation/dto/EmailRequest.java
  src/main/java/com/kosa/moimeasy/invitation/entity/Invitation.java
  src/main/java/com/kosa/moimeasy/invitation/repository/InvitationRepository.java
  src/main/java/com/kosa/moimeasy/invitation/service/InvitationService.java
  src/main/java/com/kosa/moimeasy/moeim/controller/MoeimController.java
  src/main/java/com/kosa/moimeasy/moeim/dto/MoeimDTO.java
  src/main/java/com/kosa/moimeasy/moeim/entity/Moeim.java
  src/main/java/com/kosa/moimeasy/moeim/repository/MoeimRepository.java
  src/main/java/com/kosa/moimeasy/moeim/service/MoeimService.java
  src/main/java/com/kosa/moimeasy/user/controller/UserController.java
  src/main/java/com/kosa/moimeasy/user/dto/UserDTO.java
  src/main/java/com/kosa/moimeasy/user/entity/User.java
  src/main/java/com/kosa/moimeasy/user/repository/UserRepository.java
  src/main/java/com/kosa/moimeasy/user/service/UserService.java
Labels: enhancement

#9 fix : 패키지 수정 중 오류 발생
  build.gradle
  src/main/java/com/kosa/moimeasy/GlobalExceptionHandler.java
  src/main/java/com/kosa/moimeasy/board/controller/BoardController.java
  src/main/java/com/kosa/moimeasy/board/dto/BoardDTO.java
  src/main/java/com/kosa/moimeasy/board/entity/Board.java
  src/main/java/com/kosa/moimeasy/board/repository/BoardRepository.java
  src/main/java/com/kosa/moimeasy/board/service/BoardService.java
  src/main/java/com/kosa/moimeasy/pay/controller/PayController.java
  src/main/java/com/kosa/moimeasy/pay/dto/PayDTO.java
  src/main/java/com/kosa/moimeasy/pay/entity/Pay.java
  src/main/java/com/kosa/moimeasy/pay/repository/PayRepository.java
  src/main/java/com/kosa/moimeasy/pay/service/PayService.java
  src/main/java/com/kosa/moimeasy/plan/controller/PlanController.java
  src/main/java/com/kosa/moimeasy/plan/dto/PlanDTO.java
  src/main/java/com/kosa/moimeasy/plan/entity/Plan.java
  src/main/java/com/kosa/moimeasy/plan/repository/PlanRepository.java
  src/main/java/com/kosa/moimeasy/plan/service/PlanService.java
  src/main/java/com/kosa/moimeasy/security/config/DataSourceConfig.java
  src/main/java/com/kosa/moimeasy/security/config/SecurityConfig.java
  src/main/java/com/kosa/moimeasy/security/config/WebConfig.java
  src/main/java/com/kosa/moimeasy/security/entity/RefreshToken.java
  src/main/java/com/kosa/moimeasy/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/kosa/moimeasy/security/provider/JwtTokenProvider.java
  src/main/java/com/kosa/moimeasy/security/repository/RefreshTokenRepository.java
  src/main/java/com/kosa/moimeasy/user/controller/LoginController.java
  src/main/java/com/kosa/moimeasy/user/controller/SignupController.java
  src/main/java/com/kosa/moimeasy/user/dto/LoginDTO.java
  src/main/java/com/kosa/moimeasy/user/excepsion/LoginException.java
  src/main/java/com/kosa/moimeasy/user/excepsion/SignupException.java
  src/main/resources/application-key.properties
Labels: bug

#12 docs: 충돌 해결
  build.gradle
  frontend/.prettierrc
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Modal.vue
  frontend/src/components/TableComponent.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/views/HomeView.vue
  frontend/src/views/WebSocketView.vue
  frontend/src/views/login/LoginView.vue
  frontend/src/views/login/SignupView.vue
  frontend/src/views/moeim/CreateMoeimView.vue
  frontend/src/views/moeim/CreateMoeimVue.vue
  frontend/src/views/moeim/EnterMoeimView.vue
  frontend/src/views/moeim/EnterMoeimVue.vue
  frontend/src/views/moeim/MoeimSelectView.vue
  frontend/src/views/user/InvitationListView.vue
  frontend/src/views/user/InviteUserView.vue
  frontend/src/views/user/InviteUserVue.vue
  frontend/src/views/user/UserManageView.vue
  frontend/src/views/user/UserManageVue.vue
  frontend/src/views/user/UserProfileView.vue
  frontend/vite.config.js
  gradlew
  src/main/java/com/kosa/moimeasy/MoimeasyApplication.java
  src/main/java/com/kosa/moimeasy/chat/controller/ChatController.java
  src/main/java/com/kosa/moimeasy/chat/dto/CreateRoomDTO.java
  src/main/java/com/kosa/moimeasy/chat/dto/SendMessageDTO.java
  src/main/java/com/kosa/moimeasy/chat/entity/ChatMessage.java
  src/main/java/com/kosa/moimeasy/chat/entity/ChatRoom.java
  src/main/java/com/kosa/moimeasy/chat/repository/ChatMessageRepository.java
  src/main/java/com/kosa/moimeasy/chat/repository/ChatRoomRepository.java
  src/main/java/com/kosa/moimeasy/chat/service/ChatService.java
  src/main/java/com/kosa/moimeasy/config/WebSocketConfig.java
  src/main/java/com/kosa/moimeasy/config/WebSocketInterceptor.java
  src/main/java/com/kosa/moimeasy/exception/ResourceNotFoundException.java
  src/main/java/com/kosa/moimeasy/invitation/controller/InvitationController.java
  src/main/java/com/kosa/moimeasy/invitation/dto/EmailRequest.java
  src/main/java/com/kosa/moimeasy/invitation/repository/InvitationRepository.java
  src/main/java/com/kosa/moimeasy/invitation/service/InvitationService.java
  src/main/java/com/kosa/moimeasy/moeim/controller/MoeimController.java
  src/main/java/com/kosa/moimeasy/moeim/dto/MoeimDTO.java
  src/main/java/com/kosa/moimeasy/moeim/entity/Moeim.java
  src/main/java/com/kosa/moimeasy/moeim/repository/MoeimRepository.java
  src/main/java/com/kosa/moimeasy/moeim/service/MoeimService.java
  src/main/java/com/kosa/moimeasy/user/controller/UserController.java
  src/main/java/com/kosa/moimeasy/user/dto/UserDTO.java
  src/main/java/com/kosa/moimeasy/user/repository/UserRepository.java
  src/main/java/com/kosa/moimeasy/user/service/UserService.java
  src/main/resources/application.properties
Labels: enhancement

#13 docs: 문서수정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/vite.config.js
  src/main/java/com/kosa/moimeasy/security/provider/JwtTokenProvider.java
Labels: enhancement

#15 feat: 로그인 기능 및 회원가입 기능 추가
  build.gradle
  src/main/java/com/kosa/moimeasy/GlobalExceptionHandler.java
  src/main/java/com/kosa/moimeasy/moeim/service/MoeimService.java
  src/main/java/com/kosa/moimeasy/security/config/DataSourceConfig.java
  src/main/java/com/kosa/moimeasy/security/config/RedisConfig.java
  src/main/java/com/kosa/moimeasy/security/config/SecurityConfig.java
  src/main/java/com/kosa/moimeasy/security/dto/AccessTokenDTO.java
  src/main/java/com/kosa/moimeasy/security/dto/TokenResponseDTO.java
  src/main/java/com/kosa/moimeasy/security/entity/RefreshTokenRedis.java
  src/main/java/com/kosa/moimeasy/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/kosa/moimeasy/security/provider/JwtTokenProvider.java
  src/main/java/com/kosa/moimeasy/security/repository/MemberRepository.java
  src/main/java/com/kosa/moimeasy/security/repository/RefreshTokenRepository.java
  src/main/java/com/kosa/moimeasy/security/repository/RoleRepository.java
  src/main/java/com/kosa/moimeasy/security/service/CustomUserDetailsService.java
  src/main/java/com/kosa/moimeasy/user/controller/LoginController.java
  src/main/java/com/kosa/moimeasy/user/controller/SignupController.java
  src/main/java/com/kosa/moimeasy/user/dto/SignupDTO.java
  src/main/java/com/kosa/moimeasy/user/dto/UserDTO.java
  src/main/java/com/kosa/moimeasy/user/dto/UserInfoDTO.java
  src/main/java/com/kosa/moimeasy/user/entity/Role.java
  src/main/java/com/kosa/moimeasy/user/entity/User.java
  src/main/java/com/kosa/moimeasy/user/exception/DuplicateEmailException.java
  src/main/java/com/kosa/moimeasy/user/exception/DuplicateNicknameException.java
  src/main/java/com/kosa/moimeasy/user/exception/LoginException.java
  src/main/java/com/kosa/moimeasy/user/exception/SignupException.java
  src/main/java/com/kosa/moimeasy/user/service/LoginService.java
  src/main/java/com/kosa/moimeasy/user/service/LoginServiceImpl.java
  src/main/java/com/kosa/moimeasy/user/service/SignUpService.java
  src/main/java/com/kosa/moimeasy/user/service/SignUpServiceImpl.java
  src/main/resources/application-key.properties
  src/main/resources/application.properties
Labels: enhancement

#20 fix : DB 타입에러 수정
  src/main/resources/application-key.properties
  src/main/resources/application.properties
Labels: bug, enhancement

#21 feat: vue 로그인 기능 추가 및 충돌 해결
  frontend/src/main.js
  frontend/src/views/login/LoginView.vue
  package-lock.json
  src/main/java/com/kosa/moimeasy/security/config/SecurityConfig.java
  src/main/resources/application.properties
Labels: enhancement

#22 chore : assets/icons 폴더 추가
  .gitignore
  build.gradle
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/icons/Avatar.svg
  frontend/src/assets/icons/arrowIcon.svg
  frontend/src/assets/icons/blurIcon.svg
  frontend/src/assets/icons/cartIcon.svg
  frontend/src/assets/icons/editIcon.svg
  frontend/src/assets/icons/graphIcon.svg
  frontend/src/assets/icons/logo.svg
  frontend/src/assets/icons/notebook.svg
  frontend/src/assets/icons/notifications.svg
  frontend/src/assets/icons/outlineIcon.svg
  frontend/src/assets/icons/searchIcon.svg
  frontend/src/assets/icons/settingsIcon.svg
  frontend/src/assets/icons/usersIcon.svg
  frontend/src/components/layouts/Header.vue
  frontend/src/components/layouts/NavLogo.vue
  frontend/src/components/layouts/SideBar.vue
  frontend/src/router/index.js
  frontend/src/utils/event-utils.js
  frontend/src/views/Error/Error404.vue
  frontend/src/views/schedule/Draw.vue
  frontend/src/views/schedule/components/ScheduleCalendar.style.css
  frontend/src/views/schedule/components/ScheduleCalendar.vue
  src/main/java/com/kosa/moimeasy/common/config/OpenApiConfig.java
  src/main/java/com/kosa/moimeasy/schedule/controller/ScheduleController.java
  src/main/resources/application.properties
  src/main/resources/application.yaml
Labels: enhancement

#23 feat: vue 로그인 시큐리티, jwt토큰 기능 추가
  frontend/src/axios.js
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/stores/auth.js
  frontend/src/views/login/LoginView.vue
  frontend/vite.config.js
  src/main/java/com/kosa/moimeasy/security/service/CustomUserDetailsService.java
  src/main/resources/application-key.properties
Labels: enhancement

#25 design : 404페이지 스타일 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/components/common/LoadingOverlay.vue
  frontend/src/components/layouts/Header.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/stores/pathStore.js
  frontend/src/stores/useLoadingStore.js
  frontend/src/views/Error/Error404.vue
  frontend/src/views/board/components/PostBoard.vue
  frontend/src/views/schedule/ScheduleView.vue
  frontend/src/views/schedule/components/ScheduleCalendar.vue
  frontend/src/views/user/UserManageView.vue
  frontend/src/views/user/UserProfileView.vue
  src/main/java/com/kosa/moimeasy/schedule/controller/ScheduleController.java
  src/main/java/com/kosa/moimeasy/schedule/entity/Schedule.java
  src/main/java/com/kosa/moimeasy/schedule/repository/ScheduleRepository.java
  src/main/java/com/kosa/moimeasy/schedule/service/ScheduleService.java
  src/main/java/com/kosa/moimeasy/user/entity/User.java
  src/main/java/com/kosa/moimeasy/user/service/SignUpServiceImpl.java
  src/main/resources/application-key.properties
Labels: enhancement

#26 feat: moiemId 토큰에 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/src/stores/auth.js
  frontend/src/views/login/test.vue
  src/main/java/com/kosa/moimeasy/security/dto/TokenResponseDTO.java
  src/main/java/com/kosa/moimeasy/user/controller/LoginController.java
  src/main/java/com/kosa/moimeasy/user/service/LoginServiceImpl.java
  src/main/resources/application-key.properties
Labels: enhancement

#27 docs: 채팅진짜끝
  frontend/src/components/layouts/SideBar.vue
  frontend/src/router/index.js
  frontend/src/stores/auth.js
  frontend/src/views/chat/ChatLayoutView.vue
  frontend/src/views/chat/ChatRoomListView.vue
  frontend/src/views/chat/ChatView.vue
  frontend/src/views/user/UserManageView.vue
  frontend/src/views/user/UserProfileView.vue
  src/main/java/com/kosa/moimeasy/chat/controller/ChatController.java
  src/main/java/com/kosa/moimeasy/chat/entity/ChatRoom.java
  src/main/java/com/kosa/moimeasy/chat/entity/ChatRoomUser.java
  src/main/java/com/kosa/moimeasy/chat/repository/ChatMessageRepository.java
  src/main/java/com/kosa/moimeasy/chat/repository/ChatRoomRepository.java
  src/main/java/com/kosa/moimeasy/chat/repository/ChatRoomUserRepository.java
  src/main/java/com/kosa/moimeasy/chat/service/ChatService.java
  src/main/java/com/kosa/moimeasy/security/dto/TokenResponseDTO.java
  src/main/java/com/kosa/moimeasy/user/controller/UserController.java
  src/main/java/com/kosa/moimeasy/user/entity/User.java
  src/main/java/com/kosa/moimeasy/user/service/LoginServiceImpl.java
Labels: enhancement

#28 docs:모임 만들기끝, 회원관리, 초대는 아직임
  frontend/src/views/login/LoginView.vue
  frontend/src/views/moeim/CreateMoeimView.vue
  frontend/src/views/moeim/EnterMoeimView.vue
  src/main/java/com/kosa/moimeasy/moeim/controller/MoeimController.java
Labels: documentation

#29 feat: vue 회원가입 기능 빌드업
  frontend/src/router/index.js
  frontend/src/views/login/SignupView.vue
  frontend/src/views/signup/SignupView.vue
  src/main/java/com/kosa/moimeasy/GlobalExceptionHandler.java
  src/main/java/com/kosa/moimeasy/user/controller/SignupController.java
  src/main/java/com/kosa/moimeasy/user/dto/SignupDTO.java
  src/main/java/com/kosa/moimeasy/user/exception/PasswordMismatchException.java
  src/main/java/com/kosa/moimeasy/user/service/LoginServiceImpl.java
Labels: enhancement

#30 chore: 로그인 페이지에서 회원가입 버튼 활성화 및 로그인 시 회원가입으로 들어갈 경우 메인으로 리다이렉트
  frontend/src/components/layouts/SideBar.vue
  frontend/src/router/index.js
  frontend/src/views/login/LoginView.vue
  frontend/src/views/signup/SignupView.vue
Labels: documentation

#31 feat: vue 로그아웃 기능 추가
  frontend/src/components/layouts/SideBar.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/stores/auth.js
  src/main/java/com/kosa/moimeasy/user/controller/LoginController.java
Labels: enhancement, invalid

#32 refactor : 일정추가 모달 컴포넌트 일부 수정
  frontend/src/assets/images/node.png
  frontend/src/components/layouts/Header.vue
  frontend/src/main.js
  frontend/src/presets/Noir.js
  frontend/src/views/login/LoginView.vue
  frontend/src/views/schedule/components/ScheduleCalendar.style.css
  frontend/src/views/schedule/components/ScheduleCalendar.vue
  frontend/src/views/user/UserProfileView.vue
  src/main/java/com/kosa/moimeasy/schedule/dto/ScheduleDTO.java
  src/main/java/com/kosa/moimeasy/schedule/entity/Schedule.java
  src/main/java/com/kosa/moimeasy/schedule/service/ScheduleService.java
  src/main/resources/application-key.properties
Labels: enhancement

#34 fix : Vue 파일 추가
  frontend/src/views/transaction/Category.vue
  frontend/src/views/transaction/PayMenuList.vue
  frontend/src/views/transaction/RemittanceList.vue
  frontend/src/views/transaction/TransactionList.vue
  src/main/java/com/kosa/moimeasy/user/entity/User.java
  src/main/resources/application-key.properties
Labels: documentation

#35 feat : [헤더] 로그인유저 닉네임반영
  frontend/src/App.vue
  frontend/src/components/layouts/Header.vue
  frontend/src/router/index.js
  frontend/src/views/board/BoardPostView.vue
  frontend/src/views/schedule/components/ScheduleCalendar.vue
  src/main/java/com/kosa/moimeasy/board/repository/BoardRepository.java
  src/main/java/com/kosa/moimeasy/chat/repository/ChatMessageRepository.java
  src/main/java/com/kosa/moimeasy/invitation/repository/InvitationRepository.java
  src/main/java/com/kosa/moimeasy/moeim/repository/MoeimRepository.java
  src/main/java/com/kosa/moimeasy/schedule/repository/ScheduleRepository.java
  src/main/java/com/kosa/moimeasy/user/entity/User.java
  src/main/java/com/kosa/moimeasy/user/repository/UserRepository.java
  src/main/resources/application-key.properties
Labels: bug, enhancement

#36 feat: 이메일찾기(아이디)기능 추가
  frontend/src/views/login/LoginView.vue
  src/main/java/com/kosa/moimeasy/user/controller/FindController.java
  src/main/java/com/kosa/moimeasy/user/dto/EmailFindRequest.java
  src/main/java/com/kosa/moimeasy/user/dto/EmailFindResponse.java
  src/main/java/com/kosa/moimeasy/user/exception/UserNotFoundException.java
  src/main/java/com/kosa/moimeasy/user/service/FindService.java
  src/main/java/com/kosa/moimeasy/user/service/FindServiceImpl.java
  src/test/java/com/kosa/moimeasy/transaction/TransactionRepositoryTest.java
  src/test/java/com/kosa/moimeasy/transaction/TransactionServiceTest.java
Labels: enhancement

#37 "docs: 초대가능"
  frontend/src/components/layouts/SideBar.vue
  frontend/src/router/index.js
  frontend/src/views/chat/ChatLayoutView.vue
  frontend/src/views/chat/ChatRoomListView.vue
  frontend/src/views/chat/ChatView.vue
  frontend/src/views/user/InviteUserView.vue
  frontend/src/views/user/UserManageView.vue
  src/main/java/com/kosa/moimeasy/chat/controller/ChatController.java
  src/main/java/com/kosa/moimeasy/chat/dto/CreateRoomDTO.java
  src/main/java/com/kosa/moimeasy/chat/service/ChatService.java
  src/main/java/com/kosa/moimeasy/invitation/controller/InvitationController.java
  src/main/java/com/kosa/moimeasy/invitation/repository/InvitationRepository.java
  src/main/java/com/kosa/moimeasy/invitation/service/InvitationService.java
  src/main/java/com/kosa/moimeasy/user/controller/UserController.java
  src/main/java/com/kosa/moimeasy/user/dto/UserDTO.java
  src/main/java/com/kosa/moimeasy/user/repository/UserRepository.java
  src/main/java/com/kosa/moimeasy/user/service/LoginServiceImpl.java
  src/main/java/com/kosa/moimeasy/user/service/UserService.java
  src/main/resources/application-key.properties
Labels: enhancement

#40 perf: 로그인 및 회원가입 성능 개선
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/views/find/FindEmailView.vue
  frontend/src/views/find/FindUserInfoView.vue
  frontend/src/views/find/ResetPasswordView.vue
  frontend/src/views/login/LoginView.vue
  frontend/src/views/signup/SignupView.vue
  src/main/java/com/kosa/moimeasy/user/controller/FindController.java
  src/main/java/com/kosa/moimeasy/user/dto/FindUserRequest.java
  src/main/java/com/kosa/moimeasy/user/dto/PasswordResetRequest.java
  src/main/java/com/kosa/moimeasy/user/dto/PasswordResetResponse.java
  src/main/java/com/kosa/moimeasy/user/dto/ResetPasswordDTO.java
  src/main/java/com/kosa/moimeasy/user/exception/InvalidPasswordResetException.java
  src/main/java/com/kosa/moimeasy/user/exception/MemberNotFoundException.java
  src/main/java/com/kosa/moimeasy/user/service/FindService.java
  src/main/java/com/kosa/moimeasy/user/service/FindServiceImpl.java
Labels: enhancement

#42 feat : 일정 변경 추가
  frontend/index.html
  frontend/src/assets/base.css
  frontend/src/components/layouts/Header.vue
  frontend/src/components/layouts/SideBar.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/stores/auth.js
  frontend/src/utils/image-load-utils.js
  frontend/src/utils/notification-add-utils.js
  frontend/src/views/board/BoardDetailView.vue
  frontend/src/views/board/BoardPostView.vue
  frontend/src/views/board/BoardView.vue
  frontend/src/views/schedule/components/ScheduleCalendar.vue
  frontend/src/views/user/UserProfileView.vue
  src/main/java/com/kosa/moimeasy/notification/controller/NotificationController.java
  src/main/java/com/kosa/moimeasy/notification/dto/NotificationDTO.java
  src/main/java/com/kosa/moimeasy/notification/entity/Notification.java
  src/main/java/com/kosa/moimeasy/notification/entity/NotificationEntity.java
  src/main/java/com/kosa/moimeasy/notification/repository/NotificationRepository.java
  src/main/java/com/kosa/moimeasy/notification/service/NotificationService.java
  src/main/java/com/kosa/moimeasy/schedule/controller/ScheduleController.java
  src/main/java/com/kosa/moimeasy/schedule/repository/ScheduleRepository.java
  src/main/java/com/kosa/moimeasy/schedule/service/ScheduleService.java
  src/main/java/com/kosa/moimeasy/security/config/SecurityConfig.java
  src/main/java/com/kosa/moimeasy/user/controller/UserController.java
  src/main/java/com/kosa/moimeasy/user/dto/UserDTO.java
  src/main/java/com/kosa/moimeasy/user/entity/User.java
  src/main/java/com/kosa/moimeasy/user/service/UserService.java
  src/main/resources/application-key.properties
Labels: enhancement

#43 fix: 비밀번호 초기화 오류 수정
  frontend/src/components/layouts/SideBar.vue
  frontend/src/stores/auth.js
  frontend/src/views/find/FindEmailView.vue
  frontend/src/views/find/FindUserInfoView.vue
  src/main/java/com/kosa/moimeasy/security/dto/TokenResponseDTO.java
  src/main/java/com/kosa/moimeasy/user/controller/FindController.java
  src/main/java/com/kosa/moimeasy/user/controller/LoginController.java
  src/main/java/com/kosa/moimeasy/user/service/FindService.java
  src/main/java/com/kosa/moimeasy/user/service/FindServiceImpl.java
  src/main/java/com/kosa/moimeasy/user/service/LoginServiceImpl.java
Labels: bug

#45 docs : 카테고리 차트 수정 및 DB 주소 변경
  frontend/src/views/transaction/Category.vue
  frontend/src/views/transaction/RemittanceList.vue
  frontend/src/views/transaction/TransactionList.vue
  frontend/src/views/transaction/TransactionMenuList.vue
  src/main/java/com/kosa/moimeasy/transaction/controller/TransactionController.java
  src/main/java/com/kosa/moimeasy/transaction/dto/InitialDataDto.java
  src/main/java/com/kosa/moimeasy/transaction/repository/TransactionRepository.java
  src/main/java/com/kosa/moimeasy/transaction/service/TransactionService.java
  src/main/resources/application-key.properties
Labels: enhancement

#50 refactor : 캘린더 고유한 일정 코드가지도록 createEventId매서드 수정
  frontend/src/components/layouts/SideBar.vue
  frontend/src/utils/event-utils.js
  frontend/src/utils/image-load-utils.js
  frontend/src/views/board/BoardView.vue
  src/main/java/com/kosa/moimeasy/schedule/service/ScheduleService.java
Labels: enhancement

#51 pert : 사이드바 반응형 사이즈 적용
  frontend/src/App.vue
  frontend/src/components/layouts/SideBar.vue
  frontend/src/views/user/UserProfileView.vue
Labels: enhancement

#52 feat: 회원정보수정 기능추가
  frontend/src/components/layouts/Header.vue
  frontend/src/router/index.js
  frontend/src/views/Error/Error404View.vue
  frontend/src/views/user/EditProfileView.vue
  frontend/src/views/user/UserProfileView.vue
  src/main/java/com/kosa/moimeasy/security/config/SecurityConfig.java
  src/main/java/com/kosa/moimeasy/user/controller/UserController.java
  src/main/java/com/kosa/moimeasy/user/dto/UserDTO.java
  src/main/java/com/kosa/moimeasy/user/service/UserService.java
  src/main/resources/application-key.properties
Labels: enhancement

#54 design : 차트 스타일 변경
  frontend/src/App.vue
  frontend/src/components/layouts/Header.vue
  frontend/src/main.js
  frontend/src/views/MainView.vue
  frontend/src/views/schedule/components/ScheduleCalendarMini.style.css
  frontend/src/views/schedule/components/ScheduleCalendarMini.vue
  frontend/src/views/transaction/Category.vue
  frontend/src/views/user/UserProfileView.vue
  frontend/vite.config.js
  src/main/java/com/kosa/moimeasy/common/config/WebSocketConfig.java
  src/main/java/com/kosa/moimeasy/security/config/SecurityConfig.java
  src/main/java/com/kosa/moimeasy/user/controller/UserController.java
  src/main/java/com/kosa/moimeasy/user/service/UserService.java
  src/main/resources/application-key.properties
Labels: documentation

#56 fix: 로그인 toast메세지 추가 & 리플래쉬 토큰 문제 이슈 해결(쿠키에 토큰값 들어옴)
  frontend/src/router/index.js
  frontend/src/views/login/LoginView.vue
  src/main/java/com/kosa/moimeasy/moeim/controller/MoeimController.java
  src/main/java/com/kosa/moimeasy/transaction/controller/TransactionController.java
  src/main/java/com/kosa/moimeasy/user/controller/LoginController.java
  src/main/java/com/kosa/moimeasy/user/service/LoginServiceImpl.java
Labels: bug

#57 feat: 모임 생성시 단체 톡방 생성, 모임 입장시 단체 톡방 입장
  frontend/public/guide/user.png
  frontend/src/views/HomeView.vue
  frontend/src/views/chat/ChatRoomListView.vue
  frontend/src/views/moeim/CreateMoeimView.vue
  frontend/src/views/moeim/EnterMoeimView.vue
  frontend/src/views/moeim/SettlementView.vue
  frontend/src/views/user/InviteUserView.vue
  src/main/java/com/kosa/moimeasy/chat/controller/ChatController.java
  src/main/java/com/kosa/moimeasy/chat/entity/ChatRoom.java
  src/main/java/com/kosa/moimeasy/chat/repository/ChatRoomRepository.java
  src/main/java/com/kosa/moimeasy/chat/service/ChatService.java
  src/main/java/com/kosa/moimeasy/invitation/controller/InvitationController.java
  src/main/java/com/kosa/moimeasy/invitation/service/InvitationService.java
  src/main/java/com/kosa/moimeasy/moeim/controller/MoeimController.java
  src/main/java/com/kosa/moimeasy/moeim/entity/Moeim.java
  src/main/java/com/kosa/moimeasy/moeim/service/MoeimService.java
  src/main/java/com/kosa/moimeasy/user/entity/User.java
Labels: enhancement

#59 fix : Transaction Pacakge 각 기능 컴포넌트 분리
  frontend/src/router/index.js
  frontend/src/views/MainView.vue
  frontend/src/views/moeim/MoeimSelectView.vue
  frontend/src/views/transaction/Category.vue
  frontend/src/views/transaction/CategoryChart.vue
  frontend/src/views/transaction/CategoryList.vue
  frontend/src/views/transaction/MenuList.vue
  frontend/src/views/transaction/MoeimWithdrawModal.vue
  frontend/src/views/transaction/RemittanceList.vue
  frontend/src/views/transaction/RemittanceModal.vue
  frontend/src/views/transaction/TransactionList.vue
  frontend/src/views/transaction/UserDepositModal.vue
  frontend/src/views/transaction/style/Modal.style.css
  frontend/src/views/transaction/style/Tag.style.css
  frontend/src/views/transaction/style/Transaction.style.css
  src/main/java/com/kosa/moimeasy/security/config/SecurityConfig.java
  src/main/java/com/kosa/moimeasy/transaction/dto/RemittanceDto.java
  src/main/java/com/kosa/moimeasy/transaction/dto/TransactionDto.java
  src/main/java/com/kosa/moimeasy/transaction/repository/TransactionRepository.java
  src/main/java/com/kosa/moimeasy/transaction/service/TransactionService.java
Labels: enhancement

#65 feat: css 수정
  frontend/jsconfig.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/router/index.js
  frontend/src/utils/ date-fomat-utile.js
  frontend/src/views/HomeView.vue
  frontend/src/views/find/FindEmailView.vue
  frontend/src/views/find/FindUserInfoView.vue
  frontend/src/views/find/ResetPasswordView.vue
  frontend/src/views/moeim/CreateMoeimView.vue
  frontend/src/views/moeim/EnterMoeimView.vue
  frontend/src/views/moeim/MoeimSelectView.vue
  frontend/src/views/signup/SignupView.vue
  frontend/vite.config.js
  src/main/java/com/kosa/moimeasy/settlement/controller/SettlementController.java
Labels: enhancement

#66 충돌
  frontend/src/router/index.js
  src/main/java/com/kosa/moimeasy/user/controller/FindController.java
  src/main/java/com/kosa/moimeasy/user/controller/LoginController.java
  src/main/java/com/kosa/moimeasy/user/controller/SignupController.java
  src/main/java/com/kosa/moimeasy/user/controller/UserController.java
Labels: bug, enhancement

#69 design : 메인페이지 레이아웃 조정중
  frontend/src/App.vue
  frontend/src/components/layouts/Header.vue
  frontend/src/views/MainView.vue
  frontend/src/views/gallery/GalleryView.vue
  frontend/src/views/gallery/components/GalleryFileUploader.style.css
  frontend/src/views/gallery/components/GalleryFileUploader.vue
  frontend/src/views/gallery/components/GalleryList.vue
  frontend/src/views/login/LoginView.vue
  frontend/src/views/schedule/components/ScheduleCalendarMini.style.css
  frontend/src/views/schedule/components/ScheduleCalendarMini.vue
  frontend/src/views/schedule/components/ScheduleDialog.vue
  frontend/src/views/user/components/UserProfileModal.vue
  src/main/java/com/kosa/moimeasy/attendants/controller/AttendantsController.java
  src/main/java/com/kosa/moimeasy/attendants/entity/Attendants.java
  src/main/java/com/kosa/moimeasy/attendants/repository/AttendantsRepository.java
  src/main/java/com/kosa/moimeasy/attendants/service/AttendantsService.java
  src/main/java/com/kosa/moimeasy/gallery/Gallery.java
  src/main/java/com/kosa/moimeasy/gallery/GalleryController.java
  src/main/java/com/kosa/moimeasy/gallery/GalleryRepository.java
  src/main/java/com/kosa/moimeasy/gallery/GalleryService.java
  src/main/java/com/kosa/moimeasy/gallery/dto/GalleryUploadRequest.java
  src/main/java/com/kosa/moimeasy/gallery/dto/UploadFileInfo.java
  src/main/resources/application-key.properties
Labels: enhancement

#70 feat : main css 추가
  frontend/src/assets/images/pexels-photo-7130555.png
  frontend/src/utils/date-fomat-utile.js
  frontend/src/views/MainView.vue
  frontend/src/views/user/EditProfileView.vue
  src/main/resources/application-key.properties
Labels: enhancement

#71 refactor : 메인페이지 컴포넌트 작업중
  frontend/src/views/MainView.vue
  frontend/src/views/board/components/BoardViewMini.vue
Labels: enhancement

#78 design : 갤러리 업로드버튼위치 변경
  frontend/src/App.vue
  frontend/src/views/gallery/GalleryView.vue
Labels: enhancement

#79 style: main chat 수정
  frontend/src/views/MainView.vue
  frontend/src/views/chat/ChatView.vue
Labels: enhancement
